Update u-boot_%.bbappend
This change solves according this link 
https://www.yoctoproject.org/pipermail/meta-xilinx/2018-July/004005.html
the issue below. It seems to work for me.

ERROR: Nothing PROVIDES 'virtual/xilinx-platform-init' (but /home/rudi/git/poky/meta/recipes-bsp/u-boot/u-boot_2021.01.bb DEPENDS on or otherwise requires it)
platform-init PROVIDES virtual/xilinx-platform-init but was skipped: incompatible with machine zybo-zynq7 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'u-boot-zynq-uenv', 'virtual/boot-bin', 'virtual/xilinx-platform-init']